import type { Metadata } from "next";
import { Nav } from '@/components/nav'
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white">
        <Nav />
        {children}
      </body>
    </html>
  );
}

// // src/app/layout.tsx
// import { Nav } from '@/components/nav'
// import './globals.css'

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen bg-white">
//         <Nav />
//         {children}
//       </body>
//     </html>
//   )
// }
